config/routes.rb
Rails.application.routes.draw do
  get 'users/admin'
  get 'histories/userhistories'
  post 'users/admin/:id', to: 'users#def_admin', as: 'def_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }
  resources :histories
  root 'histories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :histories
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :new, :edit, :create, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  def userhistories
    @histories = History.all
  end
  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)
    @history.user = current_user
    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:title, :picture, :content, :remote_picture_url)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:admin]

  def admin
    if current_user.admin
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def def_admin
    @user = User.find(params[:id])
    @user.admin = !@user.admin
    @user.save
    redirect_to user_admin_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true, multipart: true, class: "form-horizontal") do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= form.label :title, "Título", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :title, id: :history_title, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :remote_picture_url, "URL Imagen", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= image_tag(history.picture.thumb, style: "margin-bottom: 10px; border-radius: 5px;") if history.picture? %>

        <%= form.text_field :remote_picture_url, id: :history_picture, class: "form-control" %>
      </div>
      <%= form.hidden_field :picture_cache %>
    </div>

    <div class="form-group">
      <%= form.label :content, "Descripción", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_area :content, id: :history_content, class: "form-control", rows: 10 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit "Enviar", class: "btn btn-primary" %>
        <%= link_to 'Back', histories_path, class: "btn btn-default"  %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/histories/edit.html.erb
<legend>Editar Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/index.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h3>Histories</h3>
  </div>
  <% if signed_in? %>
    <div class="col-xs-4 col-sm-2 col-md-2">
      <%= link_to 'New History', new_history_path, class: "btn btn-info btn-sm" %>
    </div>
  <% end %>
</div>

<div class="row">
  <% @histories.reverse.each do |history| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(history.picture.thumb), history) if history.picture? %>
        <div class="caption">
          <h3><%= history.title %></h3>
          <small><%= time_ago_in_words(history.created_at) %> ago</small>
          <p><%= history.content.truncate(150)  %></p>
          <p>By <%= history.user.username %></p>
          <p><%= link_to 'Show', history, class: "btn btn-primary" %>
          <% if signed_in? %> 
            <% if history.user == current_user || current_user.admin? %>
              <%= link_to 'Edit', edit_history_path(history), class: "btn btn-warning" %>
              <%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/histories/new.html.erb
<legend>Nueva Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= image_tag(@history.picture_url, style: "max-width: 100%; border-radius: 10px;") if @history.picture? %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @history.title %></h1>
          <small><%= time_ago_in_words(@history.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
      </div>

      <hr>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p><%= @history.content %></p>
        </div>
        <div class="col-md-2"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-2">
          <p><%= link_to 'Edit', edit_history_path(@history), class: "btn btn-warning btn-sm" %> <%= link_to 'Back', histories_path, class: "btn btn-info btn-sm" %></p>
        </div>
        <div class="col-md-2"></div>
      </div>

</div>

app/views/histories/userhistories.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h3>My Histories</h3>
  </div>
    <div class="col-xs-4 col-sm-2 col-md-2">
      <%= link_to 'New History', new_history_path, class: "btn btn-info btn-sm" %>
    </div>
</div>

<div class="row">
  <% @histories.reverse.each do |history| %>
    <% if history.user == current_user %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to(image_tag(history.picture.thumb), history) if history.picture? %>
          <div class="caption">
            <h3><%= history.title %></h3>
            <small><%= time_ago_in_words(history.created_at) %> ago</small>
            <p><%= history.content.truncate(150)  %></p>
            <p>By <%= history.user.username %></p>
            <p>
            <%= link_to 'Show', history, class: "btn btn-primary" %> 
            <%= link_to 'Edit', edit_history_path(history), class: "btn btn-warning" %>
            <%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictory</title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-G3G7OsJCbOk1USkOY4RfeX1z27YaWrZ1YuaQ5tbuawed9IoreRDpWpTkZLXQfPm3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Pictory</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= histories_userhistories_path %>">My Histories</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <% if signed_in? %>
            <%= current_user.email %>
          <% else %>
            Ingreso
          <% end %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if signed_in? %>
              <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Editar Usuario</a></li>
              <li><a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Cerrar Sesión</a></li>
            <% else %>
              <li><a class="dropdown-item" href="<%= new_user_registration_path %>">Crear Usuario</a></li>
              <li><a class="dropdown-item" href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>